title: EBSCO Koha Plugin
description: Integrate results and functionality from the EDSAPI into Koha
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/ebsco/edsapi-koha-plugin/raw/master/eds_plugin_17.05.kpz